/**
 * Every artifact `merge-main-regenerating.sh` takes from main must be
 * REGENERATED by it (#1608).
 *
 * The script resolves a conflicted generated artifact with
 * `git checkout --theirs`, which DISCARDS this branch's copy. That is only
 * correct if something afterwards re-derives the file from the merged sources.
 * The pairing is the script's entire safety argument, and it was broken for one
 * of the four:
 *
 *     tests/contracts/__snapshots__/api-schemas.test.ts.snap
 *
 * was on the take-main's-copy list with **no** regeneration step — the script
 * ran `db:generate`, `openapi:generate` and `routes:inventory`, and jest not at
 * all. So a branch that added or renamed a component schema had its snapshot
 * entry discarded and never restored, and `api-schemas.test.ts` then failed in
 * CI with "New snapshot was not written" — which reads as a test problem rather
 * than as a merge resolution, and is one `-u` away from looking like a flake.
 *
 * ## Why the population is DERIVED from the script
 *
 * A guard listing four paths would pass forever while a fifth was added to the
 * enumeration. The list here is PARSED out of the script's own `case` arm, so
 * adding a path there without a regeneration step fails this test and names it.
 * That is the direction the bug actually arrived from: the snapshot was added
 * to the discard list (correctly — a textual snapshot merge is meaningless)
 * without anyone adding the matching `-u` run.
 *
 * ## Not a merge driver, and that is settled
 *
 * The appealing fix — a `.gitattributes` driver that regenerates — was built
 * and measured in #1401 and is BANNED by
 * `tests/guards/generated-artifacts-have-no-merge-driver.test.ts`. A merge
 * driver runs before git writes the merged sources, so it regenerates from the
 * PRE-merge tree and silently drops a change. I rebuilt it anyway for #1608,
 * measured the same thing from scratch, and that guard is what stopped me. The
 * ordering — merge first, regenerate after — is the design, and this script is
 * where it lives.
 */
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const SCRIPT_REL = 'scripts/merge-main-regenerating.sh';
const script = readFileSync(join(ROOT, SCRIPT_REL), 'utf8');

/**
 * The script with its COMMENTS and MESSAGE TEXT removed.
 *
 * Every assertion below must run against this and not against the raw source,
 * and the reason is a mutation that survived. Deleting the snapshot
 * regeneration — the exact bug this guard exists for — left the guard GREEN,
 * because the `else` branch's advice to the user still reads:
 *
 *     echo "         CI=1 npx jest tests/contracts/api-schemas.test.ts -u"
 *
 * so a pattern looking for that command still matched. The guard was asserting
 * "this string appears somewhere in the file", which a help message satisfies
 * forever. What it must assert is that the command is EXECUTED.
 */
const code = script
    .split('\n')
    .filter((l) => !l.trimStart().startsWith('#'))
    .filter((l) => !/^\s*(echo|printf)\b/.test(l))
    .join('\n');

/**
 * What re-derives each discarded path. A path appearing on the discard list
 * with no entry here is unaccounted for, which is the failure this guard is
 * about — so the map is matched against the PARSED list rather than used as the
 * list.
 */
const REGENERATOR: Readonly<Record<string, RegExp>> = {
    'src/generated/openapi.json': /npm run openapi:generate/,
    'src/generated/route-inventory.json': /npm run routes:inventory/,
    'tests/contracts/__snapshots__/api-schemas.test.ts.snap':
        /jest tests\/contracts\/api-schemas\.test\.ts -u/,
    // Not generated from source: the script re-applies this branch's dependency
    // DECLARATIONS into main's lockfile with an explicit node block, rather than
    // regenerating. Accounted for here so it is not mistaken for an omission.
    'package-lock.json': /lock\.packages\[""\]\.dependencies/,
};

/** The paths the script resolves by taking main's copy. */
function discardedPaths(): string[] {
    // The `case` arm listing them, up to the `)` that closes the pattern.
    const arm = /\n\s*(package-lock\.json(?:[\s\S]*?))\)\n/.exec(script);
    if (!arm) return [];
    return arm[1]
        .split('|')
        .map((p) => p.replace(/\\/g, '').trim())
        .filter((p) => p.length > 0 && !p.includes(' '));
}

describe('the merge helper regenerates everything it discards', () => {
    it('control: the comment/message stripper really strips, and keeps code', () => {
        // An empty `code` would fail the positive assertions below for the
        // wrong reason, and a stripper that removed nothing would restore the
        // bug this guard missed once already.
        expect(code.length).toBeGreaterThan(200);
        expect(code).toContain('git checkout --theirs');
        // A line that exists ONLY inside an echo must be gone.
        expect(script).toContain('Nothing has been committed');
        expect(code).not.toContain('Nothing has been committed');
    });

    it('control: the discard list was actually found', () => {
        // Without this the comparisons below run over an empty set, which is
        // agreement and worthless. The regex over a shell `case` arm is the
        // fragile part — reformatting the script would silently empty it.
        expect(discardedPaths().length).toBeGreaterThanOrEqual(4);
    });

    it('the script still exists where the convention says', () => {
        // If it is renamed, every rule here is vacuous rather than failing.
        expect(existsSync(join(ROOT, SCRIPT_REL))).toBe(true);
    });

    it.each(discardedPaths())('%s is re-derived after being discarded', (path) => {
        const pattern = REGENERATOR[path];

        // A path on the discard list that nobody has accounted for. The fix is
        // to add its regenerator — or, if it is not generated, to record WHY it
        // is safe to take main's copy, as package-lock.json does.
        expect({ path, accountedFor: pattern != null }).toEqual({ path, accountedFor: true });
        expect({ path, regenerated: pattern.test(code) }).toEqual({ path, regenerated: true });
    });

    it('no entry in the map is stale', () => {
        // The other direction: a regenerator for a path no longer discarded
        // keeps this guard looking thorough while covering nothing.
        const live = new Set(discardedPaths());
        expect(Object.keys(REGENERATOR).filter((p) => !live.has(p))).toEqual([]);
    });

    it('the snapshot regeneration runs under CI=1', () => {
        // `api-schemas.test.ts` is a jest test and will migrate the SHARED test
        // database without it — the trap that already cost this repo once, and
        // the reason `openapi:generate` carries the same guard.
        const line = code.split('\n').find((l) => /jest tests\/contracts\/api-schemas/.test(l));
        expect(line).toBeDefined();
        expect(line).toContain('CI=1');
    });

    it('it is reachable as an npm script, not only as a path', () => {
        // The discoverability half of #1608. The script existed and solved the
        // problem; I did not know it was there, so I hand-resolved the conflict
        // and hand-serialised PRs around it instead. A tool nobody can find is
        // a tool that does not exist.
        const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
            scripts: Record<string, string>;
        };
        const entry = Object.entries(pkg.scripts).find(([, cmd]) =>
            cmd.includes('merge-main-regenerating.sh'),
        );
        expect(entry).toBeDefined();
    });
});
