/**
 * The generated token files match `design/tokens.json`.
 *
 * P2.3 made the JSON the single source for the web CSS and `design/Tokens.swift`.
 * That only buys anything while the generated files are actually regenerated:
 * a hand edit to either, or a JSON change without running the generator, puts
 * the two platforms back out of step — silently, because both files still
 * parse and the app still builds.
 *
 * So the generator's own `--check` mode runs here, inside the suite that
 * already gates every PR, rather than as a workflow step someone has to
 * remember to add to a new job.
 */
import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '../..');

describe('generated token files are in sync with design/tokens.json', () => {
    it('the inputs exist — a missing file must fail, not skip', () => {
        // If any of these vanished, `--check` below could be made to pass by
        // deleting the thing it checks.
        for (const rel of [
            'design/tokens.json',
            'src/styles/tokens.generated.css',
            'design/Tokens.swift',
            'scripts/generate-tokens.mjs',
        ]) {
            expect(fs.existsSync(path.join(ROOT, rel))).toBe(true);
        }
    });

    it('regenerating produces no change', () => {
        // `--check` writes nothing; it compares and exits 1 on drift. Running
        // the real generator rather than reimplementing its logic here is the
        // point — a second implementation could agree with itself while both
        // disagreed with the committed files.
        let out = '';
        try {
            out = execFileSync('node', ['scripts/generate-tokens.mjs', '--check'], {
                cwd: ROOT,
                encoding: 'utf8',
                stdio: ['ignore', 'pipe', 'pipe'],
            });
        } catch (err) {
            const e = err as { stdout?: string; stderr?: string };
            throw new Error(
                `design/tokens.json and the generated files disagree.\n` +
                    `Run \`npm run tokens:generate\` and commit the result.\n\n` +
                    `${e.stderr ?? ''}${e.stdout ?? ''}`,
            );
        }
        expect(out).toContain('in sync');
    });

    it('the CSS carries a do-not-edit banner naming its source', () => {
        // A generated file that does not say so gets hand-edited once and then
        // silently overwritten, losing the edit.
        const css = fs.readFileSync(path.join(ROOT, 'src/styles/tokens.generated.css'), 'utf8');
        expect(css).toContain('GENERATED by scripts/generate-tokens.mjs');
        expect(css).toContain('design/tokens.json');
        const swift = fs.readFileSync(path.join(ROOT, 'design/Tokens.swift'), 'utf8');
        expect(swift).toContain('GENERATED by scripts/generate-tokens.mjs');
    });

    it('tokens.css declares no theme tokens of its own any more', () => {
        // The whole point of the split: two sources for one value is the drift
        // this PR removes. The ONLY declarations left are the reduced-motion
        // `--duration-*` overrides, which are a media query rather than a
        // theme and stay hand-authored.
        const css = fs.readFileSync(path.join(ROOT, 'src/styles/tokens.css'), 'utf8');
        const code = css.replace(/\/\*[\s\S]*?\*\//g, '');
        const decls = code.match(/(?<![\w-])--[a-z][a-z0-9-]*\s*:/g) ?? [];
        expect(decls).toHaveLength(3);
        for (const d of decls) expect(d).toMatch(/--duration-/);
        expect(css).toContain("@import './tokens.generated.css';");
    });
});
