// GENERATED by scripts/generate-tokens.mjs from design/tokens.json.
// Do not edit: `npm run tokens:check` fails on any hand edit.
//
// Every theme is FULLY RESOLVED against dark, because Swift has no CSS
// cascade: light overrides 118 of dark's 130 tokens and highContrast only 25,
// so emitting each theme's own block alone would leave an iOS build
// missing most of its palette.
//
// 29 tokens are NOT emitted: gradients and multi-value shadows have
// no single Swift value, and iOS composes those natively. They are listed
// at the bottom of this file so the omission is visible rather than silent.

import SwiftUI

public enum AgrentTheme: String, CaseIterable, Sendable {
    case dark
    case light
    case highContrast
}

public enum AgrentColor {
    /// deepest forest — page ground (gradient base, see --grad-page)
    static func bgPage(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0196, green: 0.1373, blue: 0.1059, opacity: 1.0)
        case .light: return Color(red: 0.9569, green: 0.949, blue: 0.9294, opacity: 1.0)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        }
    }

    /// deep green — cards, panels, tables, modals, popovers
    static func bgDefault(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0392, green: 0.2, blue: 0.1529, opacity: 1.0)
        case .light: return Color(red: 0.9725, green: 0.9647, blue: 0.9529, opacity: 1.0)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        }
    }

    /// darker green — hover surfaces, pressed/active states
    static func bgMuted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0275, green: 0.1608, blue: 0.1216, opacity: 1.0)
        case .light: return Color(red: 0.9412, green: 0.9294, blue: 0.9059, opacity: 1.0)
        case .highContrast: return Color(red: 0.9098, green: 0.9098, blue: 0.9098, opacity: 1.0)
        }
    }

    /// green @ 30% — selection bg, disabled surfaces, faint tints
    static func bgSubtle(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0824, green: 0.3686, blue: 0.2824, opacity: 0.3)
        case .light: return Color(red: 0.5451, green: 0.5098, blue: 0.4627, opacity: 0.07)
        case .highContrast: return Color(red: 0.9608, green: 0.9608, blue: 0.9608, opacity: 1.0)
        }
    }

    /// lifted green — tooltips, dropdowns sitting above default
    static func bgElevated(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0549, green: 0.2588, blue: 0.1961, opacity: 1.0)
        case .light: return Color(red: 0.9922, green: 0.9882, blue: 0.9804, opacity: 1.0)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        }
    }

    /// Agrent gold — inverted surface (primary button bg)
    static func bgInverted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .light: return Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 1.0)
        case .highContrast: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        }
    }

    /// deep green backdrop behind modals/drawers
    static func bgOverlay(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0078, green: 0.0706, blue: 0.051, opacity: 0.72)
        case .light: return Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 0.45)
        case .highContrast: return Color(red: 0.0078, green: 0.0706, blue: 0.051, opacity: 0.72)
        }
    }

    /// the flag's white — headings, selected items, bold labels
    static func contentEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        case .light: return Color(red: 0.102, green: 0.102, blue: 0.102, opacity: 1.0)
        case .highContrast: return Color(red: 0.0, green: 0.0, blue: 0.0, opacity: 1.0)
        }
    }

    /// green-tinted white — body text, table cells, default content
    static func contentDefault(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8627, green: 0.9216, blue: 0.8941, opacity: 1.0)
        case .light: return Color(red: 0.2392, green: 0.2392, blue: 0.2392, opacity: 1.0)
        case .highContrast: return Color(red: 0.0784, green: 0.0784, blue: 0.0784, opacity: 1.0)
        }
    }

    /// pale sage — secondary text, placeholders, captions (AA, 7.7:1 on bg-default)
    static func contentMuted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.6627, green: 0.7804, blue: 0.7333, opacity: 1.0)
        case .light: return Color(red: 0.3216, green: 0.3216, blue: 0.3216, opacity: 1.0)
        case .highContrast: return Color(red: 0.2275, green: 0.2275, blue: 0.2275, opacity: 1.0)
        }
    }

    /// deeper sage — disabled text, hints, tertiary info (AA, 5.4:1 on bg-default)
    static func contentSubtle(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.5412, green: 0.6902, blue: 0.6314, opacity: 1.0)
        case .light: return Color(red: 0.4196, green: 0.4196, blue: 0.4196, opacity: 1.0)
        case .highContrast: return Color(red: 0.3333, green: 0.3333, blue: 0.3333, opacity: 1.0)
        }
    }

    /// --content-link
    static func contentLink(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .light: return Color(red: 0.5412, green: 0.3843, blue: 0.0, opacity: 1.0)
        case .highContrast: return Color(red: 0.3529, green: 0.2471, blue: 0.0235, opacity: 1.0)
        }
    }

    /// --bubble-own
    static func bubbleOwn(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 0.16)
        case .light: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 0.16)
        case .highContrast: return Color(red: 0.9098, green: 0.9098, blue: 0.9098, opacity: 1.0)
        }
    }

    /// --bubble-other
    static func bubbleOther(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0549, green: 0.2588, blue: 0.1961, opacity: 1.0)
        case .light: return Color(red: 0.9922, green: 0.9882, blue: 0.9804, opacity: 1.0)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        }
    }

    /// --presence-online
    static func presenceOnline(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.3725, green: 0.8902, blue: 0.6078, opacity: 1.0)
        case .light: return Color(red: 0.0549, green: 0.3882, blue: 0.1961, opacity: 1.0)
        case .highContrast: return Color(red: 0.0431, green: 0.3647, blue: 0.1176, opacity: 1.0)
        }
    }

    /// --presence-away
    static func presenceAway(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9843, green: 0.749, blue: 0.1412, opacity: 1.0)
        case .light: return Color(red: 0.5725, green: 0.2588, blue: 0.0392, opacity: 1.0)
        case .highContrast: return Color(red: 0.4784, green: 0.3098, blue: 0.0, opacity: 1.0)
        }
    }

    /// --presence-offline
    static func presenceOffline(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.5412, green: 0.6902, blue: 0.6314, opacity: 1.0)
        case .light: return Color(red: 0.4196, green: 0.4196, blue: 0.4196, opacity: 1.0)
        case .highContrast: return Color(red: 0.3333, green: 0.3333, blue: 0.3333, opacity: 1.0)
        }
    }

    /// --unread
    static func unread(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .light: return Color(red: 0.5412, green: 0.3843, blue: 0.0, opacity: 1.0)
        case .highContrast: return Color(red: 0.3529, green: 0.2471, blue: 0.0235, opacity: 1.0)
        }
    }

    /// deepest forest — ink on inverted (gold) + solid-status surfaces
    static func contentInverted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0157, green: 0.1098, blue: 0.0824, opacity: 1.0)
        case .light: return Color(red: 0.9804, green: 0.9765, blue: 0.9686, opacity: 1.0)
        case .highContrast: return Color(red: 0.0157, green: 0.1098, blue: 0.0824, opacity: 1.0)
        }
    }

    /// green border — standard borders
    static func borderDefault(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0902, green: 0.3333, blue: 0.2471, opacity: 1.0)
        case .light: return Color(red: 0.898, green: 0.8863, blue: 0.8706, opacity: 1.0)
        case .highContrast: return Color(red: 0.1686, green: 0.1686, blue: 0.1686, opacity: 1.0)
        }
    }

    /// green @ 55% — soft dividers, card edges
    static func borderSubtle(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0902, green: 0.3333, blue: 0.2471, opacity: 0.55)
        case .light: return Color(red: 0.898, green: 0.8863, blue: 0.8706, opacity: 0.6)
        case .highContrast: return Color(red: 0.5412, green: 0.5412, blue: 0.5412, opacity: 1.0)
        }
    }

    /// brighter green — focused inputs, emphasized outlines
    static func borderEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.1647, green: 0.498, blue: 0.3686, opacity: 1.0)
        case .light: return Color(red: 0.7882, green: 0.7725, blue: 0.7451, opacity: 1.0)
        case .highContrast: return Color(red: 0.0, green: 0.0, blue: 0.0, opacity: 1.0)
        }
    }

    /// recessed work plane — deepest
    static func canvasSurface(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0157, green: 0.1059, blue: 0.0784, opacity: 1.0)
        case .light: return Color(red: 0.9255, green: 0.9137, blue: 0.8824, opacity: 1.0)
        case .highContrast: return Color(red: 0.0157, green: 0.1059, blue: 0.0784, opacity: 1.0)
        }
    }

    /// workspace frame + chrome strips
    static func canvasFrame(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0314, green: 0.1804, blue: 0.1333, opacity: 1.0)
        case .light: return Color(red: 0.9843, green: 0.9804, blue: 0.9725, opacity: 1.0)
        case .highContrast: return Color(red: 0.0314, green: 0.1804, blue: 0.1333, opacity: 1.0)
        }
    }

    /// dot grid — faint sage light
    static func canvasGrid(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.5882, green: 0.8039, blue: 0.698, opacity: 0.1)
        case .light: return Color(red: 0.2902, green: 0.251, blue: 0.2039, opacity: 0.12)
        case .highContrast: return Color(red: 0.5882, green: 0.8039, blue: 0.698, opacity: 0.1)
        }
    }

    /// default connection stroke (R27-PR-B)
    static func canvasEdge(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.1961, green: 0.4824, blue: 0.3686, opacity: 1.0)
        case .light: return Color(red: 0.6784, green: 0.6392, blue: 0.5843, opacity: 1.0)
        case .highContrast: return Color(red: 0.1961, green: 0.4824, blue: 0.3686, opacity: 1.0)
        }
    }

    /// node fill — elevated flow card
    static func canvasNode(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0745, green: 0.3137, blue: 0.2196, opacity: 1.0)
        case .light: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        case .highContrast: return Color(red: 0.0745, green: 0.3137, blue: 0.2196, opacity: 1.0)
        }
    }

    /// node fill — context (quieter)
    static func canvasNodeMuted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0471, green: 0.2275, blue: 0.1608, opacity: 1.0)
        case .light: return Color(red: 0.9569, green: 0.9451, blue: 0.9176, opacity: 1.0)
        case .highContrast: return Color(red: 0.0471, green: 0.2275, blue: 0.1608, opacity: 1.0)
        }
    }

    /// hairline inside the workspace
    static func canvasBorder(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.5882, green: 0.8039, blue: 0.698, opacity: 0.2)
        case .light: return Color(red: 0.2902, green: 0.251, blue: 0.2039, opacity: 0.14)
        case .highContrast: return Color(red: 0.5882, green: 0.8039, blue: 0.698, opacity: 0.2)
        }
    }

    /// Agrent metallic gold — brand accent, links
    static func brandDefault(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .light: return Color(red: 0.5412, green: 0.3843, blue: 0.0, opacity: 1.0)
        case .highContrast: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        }
    }

    /// dark goldenrod — primary buttons, active brand
    static func brandEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.7216, green: 0.5255, blue: 0.0431, opacity: 1.0)
        case .light: return Color(red: 0.4784, green: 0.3451, blue: 0.0, opacity: 1.0)
        case .highContrast: return Color(red: 0.7216, green: 0.5255, blue: 0.0431, opacity: 1.0)
        }
    }

    /// lighter gold — hover accent
    static func brandMuted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8941, green: 0.7725, blue: 0.3608, opacity: 1.0)
        case .light: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .highContrast: return Color(red: 0.8941, green: 0.7725, blue: 0.3608, opacity: 1.0)
        }
    }

    /// gold @ 16% — brand tint backgrounds
    static func brandSubtle(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 0.16)
        case .light: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 0.16)
        case .highContrast: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 0.16)
        }
    }

    /// the flag's white, ground-tinted — secondary brand
    static func brandSecondaryDefault(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8627, green: 0.9216, blue: 0.8941, opacity: 1.0)
        case .light: return Color(red: 0.1176, green: 0.2275, blue: 0.5412, opacity: 1.0)
        case .highContrast: return Color(red: 0.8627, green: 0.9216, blue: 0.8941, opacity: 1.0)
        }
    }

    /// deepest rung — bottom band stop, active surface tint
    static func brandSecondaryEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.6627, green: 0.7804, blue: 0.7333, opacity: 1.0)
        case .light: return Color(red: 0.0902, green: 0.1451, blue: 0.3294, opacity: 1.0)
        case .highContrast: return Color(red: 0.6627, green: 0.7804, blue: 0.7333, opacity: 1.0)
        }
    }

    /// lightest rung — band highlight midstop, hover accent
    static func brandSecondaryMuted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        case .light: return Color(red: 0.2314, green: 0.5098, blue: 0.9647, opacity: 1.0)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        }
    }

    /// @ 18% — secondary tint backgrounds
    static func brandSecondarySubtle(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8627, green: 0.9216, blue: 0.8941, opacity: 0.18)
        case .light: return Color(red: 0.1176, green: 0.2275, blue: 0.5412, opacity: 0.09)
        case .highContrast: return Color(red: 0.8627, green: 0.9216, blue: 0.8941, opacity: 0.18)
        }
    }

    /// spring green @ 16% — badge tint
    static func bgSuccess(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.3725, green: 0.8902, blue: 0.6078, opacity: 0.16)
        case .light: return Color(red: 0.0863, green: 0.502, blue: 0.2235, opacity: 0.07)
        case .highContrast: return Color(red: 0.3725, green: 0.8902, blue: 0.6078, opacity: 0.16)
        }
    }

    /// solid actionable surface (success buttons, indicator dots)
    static func bgSuccessEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0784, green: 0.7216, blue: 0.4, opacity: 1.0)
        case .light: return Color(red: 0.0157, green: 0.4706, blue: 0.3412, opacity: 1.0)
        case .highContrast: return Color(red: 0.0784, green: 0.7216, blue: 0.4, opacity: 1.0)
        }
    }

    /// bright spring green — separates from the ground
    static func contentSuccess(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.3725, green: 0.8902, blue: 0.6078, opacity: 1.0)
        case .light: return Color(red: 0.0549, green: 0.3882, blue: 0.1961, opacity: 1.0)
        case .highContrast: return Color(red: 0.0431, green: 0.3647, blue: 0.1176, opacity: 1.0)
        }
    }

    /// --border-success
    static func borderSuccess(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.3725, green: 0.8902, blue: 0.6078, opacity: 0.32)
        case .light: return Color(red: 0.0863, green: 0.502, blue: 0.2235, opacity: 0.2)
        case .highContrast: return Color(red: 0.3725, green: 0.8902, blue: 0.6078, opacity: 0.32)
        }
    }

    /// amber-500 @ 15% — badge tint
    static func bgWarning(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9608, green: 0.6196, blue: 0.0431, opacity: 0.15)
        case .light: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 0.07)
        case .highContrast: return Color(red: 0.9608, green: 0.6196, blue: 0.0431, opacity: 0.15)
        }
    }

    /// amber-600 — solid actionable surface
    static func bgWarningEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.851, green: 0.4667, blue: 0.0235, opacity: 1.0)
        case .light: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 1.0)
        case .highContrast: return Color(red: 0.851, green: 0.4667, blue: 0.0235, opacity: 1.0)
        }
    }

    /// amber-400
    static func contentWarning(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9843, green: 0.749, blue: 0.1412, opacity: 1.0)
        case .light: return Color(red: 0.5725, green: 0.2588, blue: 0.0392, opacity: 1.0)
        case .highContrast: return Color(red: 0.4784, green: 0.3098, blue: 0.0, opacity: 1.0)
        }
    }

    /// amber-500 @ 30%
    static func borderWarning(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9608, green: 0.6196, blue: 0.0431, opacity: 0.3)
        case .light: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 0.2)
        case .highContrast: return Color(red: 0.9608, green: 0.6196, blue: 0.0431, opacity: 0.3)
        }
    }

    /// alarm red @ 16% — badge tint
    static func bgError(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 0.3569, blue: 0.2902, opacity: 0.16)
        case .light: return Color(red: 0.7255, green: 0.1098, blue: 0.1098, opacity: 0.07)
        case .highContrast: return Color(red: 1.0, green: 0.3569, blue: 0.2902, opacity: 0.16)
        }
    }

    /// solid actionable surface (danger buttons, indicator dots)
    static func bgErrorEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9412, green: 0.2667, blue: 0.2196, opacity: 1.0)
        case .light: return Color(red: 0.7255, green: 0.1098, blue: 0.1098, opacity: 1.0)
        case .highContrast: return Color(red: 0.9412, green: 0.2667, blue: 0.2196, opacity: 1.0)
        }
    }

    /// bright coral-red — reads hotter than brand
    static func contentError(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 0.5412, blue: 0.4784, opacity: 1.0)
        case .light: return Color(red: 0.6, green: 0.0863, blue: 0.0863, opacity: 1.0)
        case .highContrast: return Color(red: 0.6431, green: 0.0863, blue: 0.102, opacity: 1.0)
        }
    }

    /// --border-error
    static func borderError(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 0.3569, blue: 0.2902, opacity: 0.34)
        case .light: return Color(red: 0.7255, green: 0.1098, blue: 0.1098, opacity: 0.2)
        case .highContrast: return Color(red: 1.0, green: 0.3569, blue: 0.2902, opacity: 0.34)
        }
    }

    /// blue-500 @ 15% — badge tint
    static func bgInfo(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.2314, green: 0.5098, blue: 0.9647, opacity: 0.15)
        case .light: return Color(red: 0.1137, green: 0.3059, blue: 0.8471, opacity: 0.07)
        case .highContrast: return Color(red: 0.2314, green: 0.5098, blue: 0.9647, opacity: 0.15)
        }
    }

    /// blue-600 — solid actionable surface
    static func bgInfoEmphasis(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.1451, green: 0.3882, blue: 0.9216, opacity: 1.0)
        case .light: return Color(red: 0.1137, green: 0.3059, blue: 0.8471, opacity: 1.0)
        case .highContrast: return Color(red: 0.1451, green: 0.3882, blue: 0.9216, opacity: 1.0)
        }
    }

    /// blue-400
    static func contentInfo(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.3765, green: 0.6471, blue: 0.9804, opacity: 1.0)
        case .light: return Color(red: 0.102, green: 0.2549, blue: 0.7216, opacity: 1.0)
        case .highContrast: return Color(red: 0.102, green: 0.2627, blue: 0.7216, opacity: 1.0)
        }
    }

    /// blue-500 @ 30%
    static func borderInfo(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.2314, green: 0.5098, blue: 0.9647, opacity: 0.3)
        case .light: return Color(red: 0.1137, green: 0.3059, blue: 0.8471, opacity: 0.2)
        case .highContrast: return Color(red: 0.2314, green: 0.5098, blue: 0.9647, opacity: 0.3)
        }
    }

    /// amber-400 @ 15%
    static func bgAttention(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9843, green: 0.749, blue: 0.1412, opacity: 0.15)
        case .light: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 0.07)
        case .highContrast: return Color(red: 0.9843, green: 0.749, blue: 0.1412, opacity: 0.15)
        }
    }

    /// amber-400
    static func contentAttention(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9843, green: 0.749, blue: 0.1412, opacity: 1.0)
        case .light: return Color(red: 0.5725, green: 0.2588, blue: 0.0392, opacity: 1.0)
        case .highContrast: return Color(red: 0.4784, green: 0.3098, blue: 0.0, opacity: 1.0)
        }
    }

    /// amber-400 @ 30%
    static func borderAttention(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9843, green: 0.749, blue: 0.1412, opacity: 0.3)
        case .light: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 0.2)
        case .highContrast: return Color(red: 0.9843, green: 0.749, blue: 0.1412, opacity: 0.3)
        }
    }

    /// Agrent gold focus ring
    static func ringDefault(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 0.55)
        case .light: return Color(red: 0.7216, green: 0.5255, blue: 0.0431, opacity: 0.45)
        case .highContrast: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 0.55)
        }
    }

    /// alias for components that use a different name
    static func focusRing(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 0.8039, blue: 0.0667, opacity: 0.55)
        case .light: return Color(red: 0.8157, green: 0.2902, blue: 0.0078, opacity: 0.4)
        case .highContrast: return Color(red: 1.0, green: 0.8039, blue: 0.0667, opacity: 0.55)
        }
    }

    /// --ring
    static func ring(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 0.8039, blue: 0.0667, opacity: 0.55)
        case .light: return Color(red: 0.8157, green: 0.2902, blue: 0.0078, opacity: 0.4)
        case .highContrast: return Color(red: 1.0, green: 0.8039, blue: 0.0667, opacity: 0.55)
        }
    }

    /// --ring-offset-background
    static func ringOffsetBackground(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0196, green: 0.1373, blue: 0.1059, opacity: 1.0)
        case .light: return Color(red: 0.9725, green: 0.9647, blue: 0.9529, opacity: 1.0)
        case .highContrast: return Color(red: 0.0196, green: 0.1373, blue: 0.1059, opacity: 1.0)
        }
    }

    /// --primary
    static func primary(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .light: return Color(red: 0.5412, green: 0.3843, blue: 0.0, opacity: 1.0)
        case .highContrast: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        }
    }

    /// green glass-card background
    static func glassBg(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0431, green: 0.2275, blue: 0.1725, opacity: 0.82)
        case .light: return Color(red: 0.9725, green: 0.9647, blue: 0.9529, opacity: 0.85)
        case .highContrast: return Color(red: 0.0431, green: 0.2275, blue: 0.1725, opacity: 0.82)
        }
    }

    /// --border-default @ 50% — glass-card border
    static func glassBorder(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0902, green: 0.3333, blue: 0.2471, opacity: 0.5)
        case .light: return Color(red: 0.898, green: 0.8863, blue: 0.8706, opacity: 0.5)
        case .highContrast: return Color(red: 0.0902, green: 0.3333, blue: 0.2471, opacity: 0.5)
        }
    }

    /// --btn-carbon-border
    static func btnCarbonBorder(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0, green: 0.0, blue: 0.0, opacity: 0.18)
        case .light: return Color(red: 0.2353, green: 0.1961, blue: 0.1569, opacity: 0.16)
        case .highContrast: return Color(red: 0.0, green: 0.0, blue: 0.0, opacity: 0.18)
        }
    }

    /// --ctrl-edge-rest
    static func ctrlEdgeRest(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.14)
        case .light: return Color(red: 0.2353, green: 0.1961, blue: 0.1569, opacity: 0.22)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.14)
        }
    }

    /// --ctrl-edge-hover
    static func ctrlEdgeHover(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.28)
        case .light: return Color(red: 0.2353, green: 0.1961, blue: 0.1569, opacity: 0.38)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.28)
        }
    }

    /// --btn-glass-fill-primary
    static func btnGlassFillPrimary(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9098, green: 0.7255, blue: 0.0157, opacity: 0.85)
        case .light: return Color(red: 0.8157, green: 0.2902, blue: 0.0078, opacity: 0.65)
        case .highContrast: return Color(red: 0.9098, green: 0.7255, blue: 0.0157, opacity: 0.85)
        }
    }

    /// --btn-glass-fill-secondary
    static func btnGlassFillSecondary(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0627, green: 0.2902, blue: 0.2196, opacity: 0.55)
        case .light: return Color(red: 0.2353, green: 0.1961, blue: 0.1569, opacity: 0.18)
        case .highContrast: return Color(red: 0.0627, green: 0.2902, blue: 0.2196, opacity: 0.55)
        }
    }

    /// --btn-glass-fill-destructive
    static func btnGlassFillDestructive(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9412, green: 0.2667, blue: 0.2196, opacity: 0.88)
        case .light: return Color(red: 0.8627, green: 0.149, blue: 0.149, opacity: 0.65)
        case .highContrast: return Color(red: 0.9412, green: 0.2667, blue: 0.2196, opacity: 0.88)
        }
    }

    /// --nav-gloss-highlight
    static func navGlossHighlight(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.08)
        case .light: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.7)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.08)
        }
    }

    /// --nav-row-liquid-tint
    static func navRowLiquidTint(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 0.8039, blue: 0.0667, opacity: 0.14)
        case .light: return Color(red: 0.8157, green: 0.2902, blue: 0.0078, opacity: 0.16)
        case .highContrast: return Color(red: 1.0, green: 0.8039, blue: 0.0667, opacity: 0.14)
        }
    }

    /// --nav-row-aura-color
    static func navRowAuraColor(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.18)
        case .light: return Color(red: 0.1176, green: 0.2275, blue: 0.5412, opacity: 0.18)
        case .highContrast: return Color(red: 1.0, green: 1.0, blue: 1.0, opacity: 0.18)
        }
    }

    /// --chart-series-1-start
    static func chartSeries1Start(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .light: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        case .highContrast: return Color(red: 0.8314, green: 0.6863, blue: 0.2157, opacity: 1.0)
        }
    }

    /// --chart-series-1-end
    static func chartSeries1End(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.7216, green: 0.5255, blue: 0.0431, opacity: 1.0)
        case .light: return Color(red: 0.7216, green: 0.5255, blue: 0.0431, opacity: 1.0)
        case .highContrast: return Color(red: 0.7216, green: 0.5255, blue: 0.0431, opacity: 1.0)
        }
    }

    /// --chart-series-2-start
    static func chartSeries2Start(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0235, green: 0.7137, blue: 0.8314, opacity: 1.0)
        case .light: return Color(red: 0.1176, green: 0.2275, blue: 0.5412, opacity: 1.0)
        case .highContrast: return Color(red: 0.0235, green: 0.7137, blue: 0.8314, opacity: 1.0)
        }
    }

    /// --chart-series-2-end
    static func chartSeries2End(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0549, green: 0.4549, blue: 0.5647, opacity: 1.0)
        case .light: return Color(red: 0.0902, green: 0.1451, blue: 0.3294, opacity: 1.0)
        case .highContrast: return Color(red: 0.0549, green: 0.4549, blue: 0.5647, opacity: 1.0)
        }
    }

    /// --chart-series-3-start
    static func chartSeries3Start(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.5451, green: 0.3608, blue: 0.9647, opacity: 1.0)
        case .light: return Color(red: 0.0588, green: 0.4627, blue: 0.4314, opacity: 1.0)
        case .highContrast: return Color(red: 0.5451, green: 0.3608, blue: 0.9647, opacity: 1.0)
        }
    }

    /// --chart-series-3-end
    static func chartSeries3End(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.4275, green: 0.1569, blue: 0.851, opacity: 1.0)
        case .light: return Color(red: 0.0745, green: 0.3059, blue: 0.2902, opacity: 1.0)
        case .highContrast: return Color(red: 0.4275, green: 0.1569, blue: 0.851, opacity: 1.0)
        }
    }

    /// --chart-series-4-start
    static func chartSeries4Start(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9569, green: 0.4471, blue: 0.7137, opacity: 1.0)
        case .light: return Color(red: 0.7451, green: 0.0941, blue: 0.3647, opacity: 1.0)
        case .highContrast: return Color(red: 0.9569, green: 0.4471, blue: 0.7137, opacity: 1.0)
        }
    }

    /// --chart-series-4-end
    static func chartSeries4End(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.7451, green: 0.0941, blue: 0.3647, opacity: 1.0)
        case .light: return Color(red: 0.5137, green: 0.0941, blue: 0.2627, opacity: 1.0)
        case .highContrast: return Color(red: 0.7451, green: 0.0941, blue: 0.3647, opacity: 1.0)
        }
    }

    /// --chart-series-5-start
    static func chartSeries5Start(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0627, green: 0.7255, blue: 0.5059, opacity: 1.0)
        case .light: return Color(red: 0.0824, green: 0.502, blue: 0.2392, opacity: 1.0)
        case .highContrast: return Color(red: 0.0627, green: 0.7255, blue: 0.5059, opacity: 1.0)
        }
    }

    /// --chart-series-5-end
    static func chartSeries5End(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.0157, green: 0.4706, blue: 0.3412, opacity: 1.0)
        case .light: return Color(red: 0.0784, green: 0.3255, blue: 0.1765, opacity: 1.0)
        case .highContrast: return Color(red: 0.0157, green: 0.4706, blue: 0.3412, opacity: 1.0)
        }
    }

    /// --chart-series-6-start
    static func chartSeries6Start(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.9608, green: 0.6196, blue: 0.0431, opacity: 1.0)
        case .light: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 1.0)
        case .highContrast: return Color(red: 0.9608, green: 0.6196, blue: 0.0431, opacity: 1.0)
        }
    }

    /// --chart-series-6-end
    static func chartSeries6End(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 1.0)
        case .light: return Color(red: 0.4706, green: 0.2078, blue: 0.0588, opacity: 1.0)
        case .highContrast: return Color(red: 0.7059, green: 0.3255, blue: 0.0353, opacity: 1.0)
        }
    }

    /// --chart-series-muted
    static func chartSeriesMuted(_ theme: AgrentTheme) -> Color {
        switch theme {
        case .dark: return Color(red: 0.5804, green: 0.6392, blue: 0.7216, opacity: 0.32)
        case .light: return Color(red: 0.4706, green: 0.4431, blue: 0.4235, opacity: 0.28)
        case .highContrast: return Color(red: 0.5804, green: 0.6392, blue: 0.7216, opacity: 0.32)
        }
    }
}

public enum AgrentDuration {
    /// Milliseconds.
    static func durationFast(_ theme: AgrentTheme) -> Double {
        switch theme {
        case .dark: return 100.0
        case .light: return 100.0
        case .highContrast: return 100.0
        }
    }

    static func durationDefault(_ theme: AgrentTheme) -> Double {
        switch theme {
        case .dark: return 150.0
        case .light: return 150.0
        case .highContrast: return 150.0
        }
    }

    static func durationSlow(_ theme: AgrentTheme) -> Double {
        switch theme {
        case .dark: return 300.0
        case .light: return 300.0
        case .highContrast: return 300.0
        }
    }

    static func chartHoverDuration(_ theme: AgrentTheme) -> Double {
        switch theme {
        case .dark: return 200.0
        case .light: return 200.0
        case .highContrast: return 200.0
        }
    }

    static func chartFlowDuration(_ theme: AgrentTheme) -> Double {
        switch theme {
        case .dark: return 1400.0
        case .light: return 1400.0
        case .highContrast: return 1400.0
        }
    }

    static func chartMountDuration(_ theme: AgrentTheme) -> Double {
        switch theme {
        case .dark: return 600.0
        case .light: return 600.0
        case .highContrast: return 600.0
        }
    }

    static func chartBubbleDuration(_ theme: AgrentTheme) -> Double {
        switch theme {
        case .dark: return 520.0
        case .light: return 520.0
        case .highContrast: return 520.0
        }
    }
}

public enum AgrentMetric {
    /// Points, taken from the web token's px value.
    static func glassBlur(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 12.0
        case .light: return 12.0
        case .highContrast: return 12.0
        }
    }

    static func radiusSm(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 6.0
        case .light: return 6.0
        case .highContrast: return 6.0
        }
    }

    static func radius(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 8.0
        case .light: return 8.0
        case .highContrast: return 8.0
        }
    }

    static func radiusLg(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 12.0
        case .light: return 12.0
        case .highContrast: return 12.0
        }
    }

    static func radiusXl(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 16.0
        case .light: return 16.0
        case .highContrast: return 16.0
        }
    }

    static func radiusFull(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 9999.0
        case .light: return 9999.0
        case .highContrast: return 9999.0
        }
    }

    static func btnGlassBlur(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 12.0
        case .light: return 12.0
        case .highContrast: return 12.0
        }
    }

    static func chartHoverPopDistance(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 4.0
        case .light: return 4.0
        case .highContrast: return 4.0
        }
    }

    static func chartHoverLift(_ theme: AgrentTheme) -> CGFloat {
        switch theme {
        case .dark: return 2.0
        case .light: return 2.0
        case .highContrast: return 2.0
        }
    }
}

// Not emitted (gradients / multi-value shadows / non-scalar):
//   --grad-page
//   --canvas-shadow
//   --canvas-recess
//   --grad-gold
//   --font-display
//   --font-heading
//   --shadow-sm
//   --shadow
//   --shadow-lg
//   --btn-carbon-overlay
//   --btn-carbon-bevel
//   --btn-carbon-grain
//   --btn-ambient-rest
//   --btn-ambient-hover
//   --btn-ambient-press
//   --btn-ambient-focus
//   --btn-iridescent-gradient
//   --btn-gradient-primary
//   --btn-aura-primary
//   --btn-aura-neutral
//   --ctrl-edge-focus
//   --btn-glass-tint
//   --btn-glass-edge
//   --btn-glass-inner
//   --btn-glass-shadow
//   --nav-band-glow
//   --nav-band-glow-active
//   --nav-bevel-shadow
//   --chart-soft-shadow
