/**
 * GET /api/openapi — the OpenAPI document, behind the session gate.
 *
 * ## Why it is a route and not a file in public/
 *
 * It used to be `public/openapi.json`, which Next's static handler serves
 * before any application code runs: not gated by `src/middleware.ts`, not
 * referenced by `isPublicPath`, not touched by the Caddyfile. Anonymous by
 * construction.
 *
 * That cost nothing while the document was empty — it described zero endpoints
 * (#944: 47 component schemas, no paths, because nothing ever called
 * `registerPath`). Filling it in changes that: a complete spec is a complete
 * map of the API surface, and publishing one anonymously is a decision, not a
 * side effect of fixing the generator. The product owner chose to gate it.
 *
 * ## The gate is the middleware's, deliberately
 *
 * This route adds no check of its own. `src/middleware.ts` verifies the JWT
 * for every API route that is not in `PUBLIC_PATH_PREFIXES`, and answers an
 * unauthenticated one with 401 JSON rather than a redirect. `/api/openapi` is
 * not in that list, so any signed-in user may read the spec and nobody else
 * can — which is the intended posture: it stops anonymous enumeration without
 * making the document useless to the clients that need it.
 *
 * NOT `isDocsEnabled()`, which the Swagger UI route uses: that hard-404s under
 * `NODE_ENV=production`, and staging runs as production. Gating the spec that
 * way would make it unavailable in every deployed environment, including to
 * the native client being written against it.
 *
 * The document is IMPORTED rather than read from disk, so it is bundled with
 * the route. A `readFileSync` of a repo-relative path is not reliable in the
 * runtime image, where the source tree is not present.
 */
import { NextResponse } from 'next/server';
import { withApiErrorHandling } from '@/lib/errors/api';
import spec from '@/generated/openapi.json';

export const GET = withApiErrorHandling(async () => {
    return NextResponse.json(spec, {
        headers: {
            // Regenerated by `npm run openapi:generate` and committed, so it
            // changes only with a deploy — but it is per-session gated, so it
            // must never land in a shared cache.
            'Cache-Control': 'private, no-store',
            'Content-Type': 'application/json; charset=utf-8',
        },
    });
});
