/**
 * Server-composed journal titles (#1073).
 *
 * Two properties are load-bearing and neither is obvious from the columns:
 *
 *  • A descriptor and its rendering are written TOGETHER. A `title` without
 *    its `titleKey` is an untranslatable sentence — the defect this replaces.
 *    A `titleKey` whose params disagree with `title` is worse: a reader that
 *    resolves the key shows something different from a reader that does not.
 *
 *  • The legacy parser splits on the LAST ` to `, so a product name
 *    containing the separator survives. The 11 rows it rewrites are in a
 *    legally-filed register, and the backfill corroborates its parse against
 *    the linked operation — a parser that silently mis-split would make that
 *    corroboration fail and the row be skipped, which is safe, but only
 *    because the parse is conservative in this direction.
 */
import {
    composeInputApplicationTitle,
    parseLegacyComposedTitle,
    isAutoGeneratedTitle,
    AUTO_TITLE_KEYS,
    AUTO_TITLE_FALLBACK_LOCALE,
} from '@/lib/journal/auto-title';

describe('composing a title', () => {
    it('returns the rendering and the descriptor together', async () => {
        const c = await composeInputApplicationTitle({ product: 'МАП 11-52-0', parcel: '15655-19' });
        expect(c.titleKey).toBe(AUTO_TITLE_KEYS.inputApplication);
        expect(c.titleParams).toEqual({ product: 'МАП 11-52-0', parcel: '15655-19' });
        // The rendering must actually contain what the params say. A template
        // that silently dropped a placeholder would still "render".
        expect(c.title).toContain('МАП 11-52-0');
        expect(c.title).toContain('15655-19');
    });

    it('renders no English verb — the type chip carries the category', async () => {
        // «Внасяне на препарат» sits beside this string. A title opening with
        // a competing verb would assert two categories for one event; the old
        // English was accidentally immune because it read as machine
        // metadata. So the composed title names things and classifies nothing.
        const c = await composeInputApplicationTitle({ product: 'Karate Zeon', parcel: 'Block A' });
        expect(c.title).not.toMatch(/Applied|Приложен|Внесен/i);
    });

    it('falls back to Bulgarian, not the unauthenticated default', async () => {
        // DEFAULT_LOCALE is `en` for signed-out surfaces. A journal entry is
        // read by a member of a Bulgarian farm, so this deliberately differs.
        expect(AUTO_TITLE_FALLBACK_LOCALE).toBe('bg');
    });
});

describe('recognising a server-composed title', () => {
    it('keys on the descriptor, never on the text', () => {
        expect(isAutoGeneratedTitle({ titleKey: AUTO_TITLE_KEYS.inputApplication })).toBe(true);
        expect(isAutoGeneratedTitle({ titleKey: null })).toBe(false);
        expect(isAutoGeneratedTitle({})).toBe(false);
        // An operator who types this exact sentence still owns their entry.
        expect(isAutoGeneratedTitle({ titleKey: '' })).toBe(false);
    });
});

describe('parsing a legacy English title', () => {
    it('recovers product and parcel', () => {
        expect(parseLegacyComposedTitle('Applied Generic MAP 11-52-0 to 15655-19')).toEqual({
            product: 'Generic MAP 11-52-0',
            parcel: '15655-19',
        });
    });

    it('splits on the LAST separator, so a product containing " to " survives', () => {
        // The reason the group is GREEDY. A lazy one splits on the FIRST
        // separator and yields product "Ready" / parcel "Use 5 to North
        // Block" — which is how this was first written, and what this
        // assertion caught.
        expect(parseLegacyComposedTitle('Applied Ready to Use 5 to North Block')).toEqual({
            product: 'Ready to Use 5',
            parcel: 'North Block',
        });
    });

    it('a mis-split is caught by corroboration, not by the regex', () => {
        // A PARCEL containing the separator splits the other way, and no
        // single regex fixes both. The backfill compares its parse against
        // the linked operation and SKIPS a disagreement, so this row is
        // reported rather than rewritten wrongly.
        expect(parseLegacyComposedTitle('Applied Urea to Field to Barn')).toEqual({
            product: 'Urea to Field',
            parcel: 'Barn',
        });
    });

    it('handles a parcel name with spaces', () => {
        expect(parseLegacyComposedTitle('Applied Urea to North Block 2')).toEqual({
            product: 'Urea',
            parcel: 'North Block 2',
        });
    });

    it('returns null for anything a person wrote', () => {
        // This is what lets the backfill tell composed rows from typed ones
        // in data written before any provenance column existed.
        expect(parseLegacyComposedTitle('Напръскахме блок 3')).toBeNull();
        expect(parseLegacyComposedTitle('Applied nitrogen')).toBeNull();
        expect(parseLegacyComposedTitle('')).toBeNull();
        expect(parseLegacyComposedTitle('Reapplied Urea to Block 1')).toBeNull();
    });

    it('round-trips: a parse of the old shape feeds a valid compose', async () => {
        const parsed = parseLegacyComposedTitle('Applied Generic Compound NPK 15-15-15 to 15655-19');
        expect(parsed).not.toBeNull();
        const c = await composeInputApplicationTitle(parsed!);
        expect(c.titleParams).toEqual(parsed);
        expect(c.title).toContain('Generic Compound NPK 15-15-15');
    });
});

/**
 * The descriptor has NO consumer today, and that is why this block exists.
 *
 * The native client renders `title` unconditionally and does not resolve
 * `titleKey` — correctly, since this app has one language and resolving would
 * only add a way for a stale key to paint over an operator's correction. The
 * web does not resolve it either. So `journal.autoTitle.*` is a mechanism
 * nothing exercises.
 *
 * That is precisely the shape this repo keeps getting caught by: a guard can
 * see that a code EXISTS, it cannot see that anyone consumes it, and an
 * unexercised mechanism rots silently. `no-server-authored-user-copy` proves
 * its exemption against a synthetic fixture for the same reason — an
 * exemption nothing exercises is one nobody can trust.
 *
 * So these assertions stand in for the consumer that does not exist yet. They
 * would fail if the key were deleted, if a locale lost it, or if the
 * placeholder names drifted from what the writer stores — each of which
 * would make every descriptor already in the database unresolvable, which is
 * the one failure the descriptor exists to prevent.
 */
describe('the descriptor is RESOLVABLE — the consumer that does not exist yet', () => {
    const { translateFor } = jest.requireActual<
        typeof import('@/lib/i18n/server-messages')
    >('@/lib/i18n/server-messages');

    it.each(['bg', 'en'] as const)('resolves in %s from stored params alone', async (locale) => {
        // Exactly what a future reader would have: the key and the params off
        // the row, and nothing else.
        const stored = { product: 'Generic MAP 11-52-0', parcel: '15655-19' };
        const rendered = await translateFor(locale, AUTO_TITLE_KEYS.inputApplication, stored);

        // Not `toBe(key)` — `translateFor` returns the KEY when it cannot
        // find a message, so a missing entry looks like a successful render
        // to any assertion that only checks for a non-empty string.
        expect(rendered).not.toBe(AUTO_TITLE_KEYS.inputApplication);
        expect(rendered).toContain(stored.product);
        expect(rendered).toContain(stored.parcel);
    });

    it('renders the same string the writer stored', async () => {
        // The descriptor is only worth having if re-rendering reproduces the
        // stored title. If these diverge, every backfilled row displays one
        // thing to a resolving reader and another to a non-resolving one.
        const params = { product: 'Generic Bt kurstaki', parcel: '15655-19' };
        const composed = await composeInputApplicationTitle(params);
        const reRendered = await translateFor(
            AUTO_TITLE_FALLBACK_LOCALE,
            composed.titleKey,
            composed.titleParams,
        );
        expect(reRendered).toBe(composed.title);
    });
});
