#!/usr/bin/env node
/**
 * design/tokens.json -> src/styles/tokens.generated.css + design/Tokens.swift
 *
 * P2.3. One source for both platforms, so a colour change is a one-file edit
 * and web/iOS cannot drift apart silently.
 *
 * ── what stays hand-authored, and why ──
 *
 * `src/styles/tokens.css` keeps the PROSE — 757 of its 1,170 lines were
 * comments carrying WCAG measurements, the GAP-CI-77 history, and the
 * reasoning behind each tier. That does not belong in JSON: paragraphs read
 * badly there and the next author would skip writing them. Short per-token
 * notes DO travel in the JSON, because they describe the value and belong
 * beside it.
 *
 * ── theme inheritance is load-bearing ──
 *
 * A theme declares only what it OVERRIDES: light carries 118 of dark's 130,
 * highContrast only 20. The CSS cascade handles that for the web. Swift has no
 * cascade, so each theme is emitted FULLY RESOLVED against dark — otherwise an
 * iOS high-contrast build would be missing 110 colours.
 *
 * Usage:
 *   node scripts/generate-tokens.mjs           # write both files
 *   node scripts/generate-tokens.mjs --check    # exit 1 if either is stale
 */
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(import.meta.dirname, '..');
const SRC = path.join(ROOT, 'design/tokens.json');
const CSS_OUT = path.join(ROOT, 'src/styles/tokens.generated.css');
const SWIFT_OUT = path.join(ROOT, 'design/Tokens.swift');
const CHECK = process.argv.includes('--check');

const spec = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const THEME_ORDER = ['dark', 'light', 'highContrast'];

for (const t of THEME_ORDER) {
    if (!spec.themes[t]) throw new Error(`design/tokens.json is missing theme "${t}"`);
    if (!spec.themeSelectors[t]) throw new Error(`no selector declared for theme "${t}"`);
}

// ─── CSS ────────────────────────────────────────────────────────────────────

function cssFor(theme) {
    const toks = spec.themes[theme];
    const names = Object.keys(toks);
    const width = Math.max(...names.map((n) => n.length));
    const body = names
        .map((n) => {
            const { value, note } = toks[n];
            const decl = `  --${n}:`.padEnd(width + 6) + ` ${value};`;
            return note ? `${decl}  /* ${note} */` : decl;
        })
        .join('\n');
    return `${spec.themeSelectors[theme]} {\n${body}\n}`;
}

const css = [
    '/*',
    ' * GENERATED by scripts/generate-tokens.mjs from design/tokens.json.',
    ' * Do not edit: `npm run tokens:check` fails on any hand edit, and the next',
    ' * generation would overwrite it. Change design/tokens.json instead.',
    ' *',
    ' * The reasoning behind these values lives in src/styles/tokens.css, which',
    ' * imports this file. Short per-token notes below come from the JSON.',
    ' */',
    '',
    ...THEME_ORDER.map(cssFor),
    '',
].join('\n');

// ─── Swift ──────────────────────────────────────────────────────────────────

/** Resolve `var(--x)` chains within a theme, falling back to dark. */
function resolve(theme, name, seen = new Set()) {
    if (seen.has(name)) throw new Error(`token cycle at --${name} in ${theme}`);
    seen.add(name);
    const tok = spec.themes[theme][name] ?? spec.themes.dark[name];
    if (!tok) return null;
    const m = /^var\(--([a-z0-9-]+)\)$/.exec(tok.value.trim());
    return m ? resolve(theme, m[1], seen) : tok.value.trim();
}

const HEX = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;
const RGBA = /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/;
const DURATION = /^([\d.]+)(ms|s)$/;
const LENGTH = /^([\d.]+)px$/;

function swiftColour(value) {
    const hex = HEX.exec(value);
    if (hex) {
        let h = hex[1];
        if (h.length === 3) h = h.split('').map((c) => c + c).join('');
        const a = h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1;
        const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
        return { r, g, b, a };
    }
    const rgba = RGBA.exec(value);
    if (rgba) {
        return {
            r: Number(rgba[1]) / 255,
            g: Number(rgba[2]) / 255,
            b: Number(rgba[3]) / 255,
            a: rgba[4] === undefined ? 1 : Number(rgba[4]),
        };
    }
    return null;
}

const f = (n) => n.toFixed(4).replace(/0+$/, '').replace(/\.$/, '.0');
const camel = (n) => n.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

function swift() {
    const allNames = Object.keys(spec.themes.dark);
    const colours = [];
    const durations = [];
    const lengths = [];
    const skipped = [];

    for (const name of allNames) {
        const perTheme = {};
        let kind = null;
        for (const theme of THEME_ORDER) {
            const v = resolve(theme, name);
            if (v == null) continue;
            const c = swiftColour(v);
            if (c) { perTheme[theme] = c; kind = kind ?? 'colour'; continue; }
            const d = DURATION.exec(v);
            if (d) { perTheme[theme] = Number(d[1]) * (d[2] === 's' ? 1000 : 1); kind = kind ?? 'duration'; continue; }
            const l = LENGTH.exec(v);
            if (l) { perTheme[theme] = Number(l[1]); kind = kind ?? 'length'; continue; }
            kind = 'unsupported';
        }
        if (kind === 'colour') colours.push([name, perTheme]);
        else if (kind === 'duration') durations.push([name, perTheme]);
        else if (kind === 'length') lengths.push([name, perTheme]);
        else skipped.push(name);
    }

    const colourCase = (name, perTheme) => {
        const arms = THEME_ORDER.map((t) => {
            const c = perTheme[t] ?? perTheme.dark;
            return `        case .${t}: return Color(red: ${f(c.r)}, green: ${f(c.g)}, blue: ${f(c.b)}, opacity: ${f(c.a)})`;
        }).join('\n');
        const note = spec.themes.dark[name]?.note;
        return `    /// ${note ? note.replace(/\s+/g, ' ') : `--${name}`}\n    static func ${camel(name)}(_ theme: AgrentTheme) -> Color {\n        switch theme {\n${arms}\n        }\n    }`;
    };

    const scalarCase = (name, perTheme, type) => {
        const arms = THEME_ORDER.map((t) => `        case .${t}: return ${f(perTheme[t] ?? perTheme.dark)}`).join('\n');
        return `    static func ${camel(name)}(_ theme: AgrentTheme) -> ${type} {\n        switch theme {\n${arms}\n        }\n    }`;
    };

    return [
        '// GENERATED by scripts/generate-tokens.mjs from design/tokens.json.',
        '// Do not edit: `npm run tokens:check` fails on any hand edit.',
        '//',
        '// Every theme is FULLY RESOLVED against dark, because Swift has no CSS',
        `// cascade: light overrides ${Object.keys(spec.themes.light).length} of dark's ${Object.keys(spec.themes.dark).length} tokens and highContrast only ${Object.keys(spec.themes.highContrast).length},`,
        '// so emitting each theme\'s own block alone would leave an iOS build',
        '// missing most of its palette.',
        '//',
        `// ${skipped.length} tokens are NOT emitted: gradients and multi-value shadows have`,
        '// no single Swift value, and iOS composes those natively. They are listed',
        '// at the bottom of this file so the omission is visible rather than silent.',
        '',
        'import SwiftUI',
        '',
        'public enum AgrentTheme: String, CaseIterable, Sendable {',
        ...THEME_ORDER.map((t) => `    case ${t}`),
        '}',
        '',
        'public enum AgrentColor {',
        colours.map(([n, p]) => colourCase(n, p)).join('\n\n'),
        '}',
        '',
        'public enum AgrentDuration {',
        '    /// Milliseconds.',
        durations.map(([n, p]) => scalarCase(n, p, 'Double')).join('\n\n'),
        '}',
        '',
        'public enum AgrentMetric {',
        '    /// Points, taken from the web token\'s px value.',
        lengths.map(([n, p]) => scalarCase(n, p, 'CGFloat')).join('\n\n'),
        '}',
        '',
        '// Not emitted (gradients / multi-value shadows / non-scalar):',
        ...skipped.map((n) => `//   --${n}`),
        '',
    ].join('\n');
}

const swiftSrc = swift();

if (CHECK) {
    let stale = [];
    for (const [file, want] of [[CSS_OUT, css], [SWIFT_OUT, swiftSrc]]) {
        const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
        if (have !== want) stale.push(path.relative(ROOT, file));
    }
    if (stale.length) {
        console.error(`STALE: ${stale.join(', ')}`);
        console.error('design/tokens.json changed without regenerating. Run: npm run tokens:generate');
        process.exit(1);
    }
    console.log('tokens: generated files are in sync with design/tokens.json');
    process.exit(0);
}

fs.writeFileSync(CSS_OUT, css);
fs.writeFileSync(SWIFT_OUT, swiftSrc);
console.log(`wrote ${path.relative(ROOT, CSS_OUT)} (${css.split('\n').length} lines)`);
console.log(`wrote ${path.relative(ROOT, SWIFT_OUT)} (${swiftSrc.split('\n').length} lines)`);
