/**
 * GET /api/docs — Swagger UI for the OpenAPI 3.1 spec.
 *
 * GAP-10 step 4. Renders the interactive API documentation, fetching the
 * spec from `/openapi.json` (served statically from `public/openapi.json`,
 * generated by `npm run openapi:generate`).
 *
 * ## Where it renders — LOCAL DEVELOPMENT ONLY
 *
 * `isDocsEnabled()` (see `./enabled.ts`) hard-404s under
 * `NODE_ENV=production` and `test`. This docblock used to say
 * "Development + staging: true" — **that was wrong**, and it is worth
 * naming rather than quietly deleting: `docker-compose.staging.yml:117`
 * sets `NODE_ENV: production` deliberately (GAP-03, "staging runs
 * NODE_ENV=production and is treated as production"), so staging takes the
 * same 404. To read the spec in a deployed environment, fetch
 * `/openapi.json` directly — it is not gated.
 *
 * ## The nonce is what makes this work (#798)
 *
 * Every script here MUST carry the per-request CSP nonce. Until #798 none
 * of them did, and the page had therefore **never rendered anything, in any
 * environment, for the life of the feature** — it returned HTTP 200 with
 * well-formed HTML and an empty `<div id="swagger-ui">`, because the
 * failure lives entirely in the browser console.
 *
 * `src/middleware.ts` applies CSP to every response, dev included:
 *
 *     script-src 'self' 'nonce-<…>' 'strict-dynamic' [+ 'unsafe-eval' in dev]
 *
 * There is NO `unsafe-inline` in any environment (`csp.ts:19-20`), so the
 * inline bootstrap needs a nonce. And under CSP Level 3 `'strict-dynamic'`
 * makes browsers **ignore `'self'` and every host-source expression**, so a
 * same-origin `<script src>` needs one too. Serving the assets from our own
 * origin instead of jsDelivr — the change #798 asked for — buys
 * offline/air-gapped development and drops a third-party script, but it
 * does NOT by itself make the page work. Do not remove the nonces.
 *
 * A route handler builds raw HTML, so Next's automatic nonce propagation
 * (which applies to RSC-rendered pages) never reaches it. The nonce is read
 * from the request header the middleware sets, exactly as `app/layout.tsx`
 * does.
 */
import { NextResponse } from 'next/server';
import { headers } from 'next/headers';
import { withApiErrorHandling } from '@/lib/errors/api';
import { CSP_NONCE_HEADER } from '@/lib/security/csp';
import { isDocsEnabled, docsDisabledResponse } from './enabled';

const ASSET_BASE = '/api/docs/assets';
const SWAGGER_CSS = `${ASSET_BASE}/swagger-ui.css`;
const SWAGGER_JS = `${ASSET_BASE}/swagger-ui-bundle.js`;
const SWAGGER_PRESET_JS = `${ASSET_BASE}/swagger-ui-standalone-preset.js`;

/**
 * Shown when the middleware nonce is absent.
 *
 * Deliberately NOT a silently-unstyled page: an unnonced Swagger UI renders
 * as a blank div under a banner, which is exactly how this bug survived. If
 * the nonce is missing the page says so, because a diagnosis on screen is
 * the only thing that separates "broken" from "still loading" here.
 */
function missingNoncePage(): NextResponse {
    return new NextResponse(
        `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" /><title>Agrent API docs — unavailable</title></head>
<body style="font:14px/1.6 ui-sans-serif,system-ui,sans-serif;margin:2rem;max-width:44rem">
  <h1 style="font-size:1.1rem">Interactive docs unavailable</h1>
  <p>No CSP nonce was present on this request, so Swagger UI could not be
     loaded &mdash; every script would be blocked by
     <code>script-src &#39;strict-dynamic&#39;</code> and the page would render
     empty.</p>
  <p>This means <code>src/middleware.ts</code> did not run for
     <code>/api/docs</code>. The spec itself is unaffected:
     <a href="/openapi.json">/openapi.json</a>.</p>
</body></html>`,
        {
            status: 503,
            headers: {
                'Content-Type': 'text/html; charset=utf-8',
                'Cache-Control': 'no-store',
                'X-Robots-Tag': 'noindex, nofollow',
            },
        },
    );
}

export const GET = withApiErrorHandling(async (): Promise<NextResponse> => {
    if (!isDocsEnabled()) {
        return docsDisabledResponse() as NextResponse;
    }

    const nonce = (await headers()).get(CSP_NONCE_HEADER);
    if (!nonce) return missingNoncePage();

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex, nofollow" />
  <title>Agrent API — interactive docs</title>
  <link rel="stylesheet" href="${SWAGGER_CSS}" />
  <style nonce="${nonce}">
    body { margin: 0; }
    .topbar { display: none; }
    /* Distinguish dev visually so a screenshot is unambiguous. */
    body::before {
      content: "DEVELOPMENT — interactive API docs";
      display: block;
      background: #fbbf24;
      color: #1f2937;
      padding: 6px 16px;
      font: 600 12px/1.4 ui-sans-serif, system-ui, sans-serif;
      letter-spacing: 0.06em;
      text-transform: uppercase;
    }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="${SWAGGER_JS}" nonce="${nonce}"></script>
  <script src="${SWAGGER_PRESET_JS}" nonce="${nonce}"></script>
  <script nonce="${nonce}">
    window.addEventListener('load', function () {
      window.ui = SwaggerUIBundle({
        url: '/openapi.json',
        dom_id: '#swagger-ui',
        deepLinking: true,
        layout: 'BaseLayout',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset,
        ],
      });
    });
  </script>
</body>
</html>
`;

    return new NextResponse(html, {
        status: 200,
        headers: {
            'Content-Type': 'text/html; charset=utf-8',
            'Cache-Control': 'no-store',
            'X-Robots-Tag': 'noindex, nofollow',
        },
    });
});
