/**
 * The ЕИК blind index is a DIFFERENT function from the email one.
 *
 * ## What this protects
 *
 * `encryption.ts` derives a lookup hash per identifier KIND, so that one
 * deterministic value cannot correlate a person across columns and a hash
 * leaked from one table is not a working lookup key against another. P3.4 adds
 * the second kind, `eik`, for `FarmIdentityClaim.eikHash`.
 *
 * The separation is one line — an HKDF info string in `LOOKUP_INFO` — and it
 * fails SILENTLY in both directions:
 *
 *   - A new kind that reuses `HMAC_INFO` produces hashes identical to the email
 *     index. Nothing errors; the index simply stops being domain-separated, and
 *     an `emailHash` and an `eikHash` of the same string become the same bytes.
 *   - Renaming `email`'s info string is a REHASH, not an edit. Every
 *     `User.emailHash` and `UserIdentityLink.emailAtLinkTimeHash` row was
 *     computed under the current one, and a hash has no authentication failure
 *     to signal a wrong key — the lookup MISSES. Sign-in would report no such
 *     user, and registration would succeed and create a duplicate because its
 *     uniqueness check is the same hash that now misses. Silent corruption, not
 *     an outage.
 *
 * So the first assertion below is the real invariant, and the vectors are a pin
 * that makes a rename loud.
 */

// Set BEFORE any hash is computed. `getLookupKeyMaterial()` reads the
// environment per call rather than capturing it at module load, but the derived
// key is cached by its material — so this has to be in place before the first
// call, not merely before the first assertion.
const FIXED_KEY = 'p3-4-fixed-test-lookup-key-0123456789abcdef';

import { hashForLookup, LOOKUP_KINDS } from '@/lib/security/encryption';

/** An arbitrary but fixed 9-digit ЕИК. Its value carries no meaning. */
const EIK = '831650349';

beforeAll(() => {
    process.env.LOOKUP_HMAC_KEY = FIXED_KEY;
    delete process.env.LOOKUP_HMAC_KEY_PREVIOUS;
});

describe('lookup-kind separation: eik vs email (P3.4)', () => {
    it('control: the key is pinned, so these vectors are reproducible', () => {
        // Without this the suite would silently fall back to the KEK-derived
        // material, every vector below would be machine-specific, and the pins
        // would be meaningless rather than wrong.
        expect(process.env.LOOKUP_HMAC_KEY).toBe(FIXED_KEY);
        expect(process.env.LOOKUP_HMAC_KEY).toMatch(/^.{32,}$/);
    });

    it('control: both kinds are registered', () => {
        expect(LOOKUP_KINDS).toContain('email');
        expect(LOOKUP_KINDS).toContain('eik');
    });

    it('THE INVARIANT: the same input hashes differently per kind', () => {
        // This is what a reused info string breaks, and it needs no pinned
        // vector to detect — which is why it is stated separately from them.
        expect(hashForLookup(EIK, 'eik')).not.toBe(hashForLookup(EIK, 'email'));
    });

    it('both kinds produce a 64-char hex digest', () => {
        expect(hashForLookup(EIK, 'eik')).toMatch(/^[0-9a-f]{64}$/);
        expect(hashForLookup(EIK, 'email')).toMatch(/^[0-9a-f]{64}$/);
    });

    it('each kind is deterministic', () => {
        expect(hashForLookup(EIK, 'eik')).toBe(hashForLookup(EIK, 'eik'));
        expect(hashForLookup('x@y.z', 'email')).toBe(hashForLookup('x@y.z', 'email'));
    });

    it('distinct ЕИКs do not collide', () => {
        expect(hashForLookup('831650349', 'eik')).not.toBe(hashForLookup('831650348', 'eik'));
    });

    // ── Pins ─────────────────────────────────────────────────────────
    //
    // Generated by running the implementation under FIXED_KEY, so they are
    // REGRESSION PINS rather than independently derived expectations: they
    // cannot tell you the derivation is correct, only that it has not changed.
    // That is exactly the property wanted here — the hazard is a quiet edit to
    // an info string, and these turn it into a failing test instead of a
    // product-wide lookup miss.

    it('pin: the email vector is UNCHANGED — a rename here is a rehash', () => {
        expect(hashForLookup(EIK, 'email')).toBe(
            '1689aef3c2c8e49bd5e7371d2fe13e444b13f868c14b66a2322f56afeebf9300',
        );
    });

    it('pin: the eik vector', () => {
        // Less load-bearing than the email pin — no rows exist under it yet —
        // but once claims are stored, changing this info string strands every
        // `eikHash` in the table, with the same silence.
        expect(hashForLookup(EIK, 'eik')).toBe(
            '4a31fbee9a5b50bb1d5751a4f6975471bf5210ee1f6001f39566c5d52e726424',
        );
    });
});
