/**
 * GAP-10 step 4 — Swagger UI route gating.
 *
 * Verifies that GET /api/docs is dev/staging only — production must
 * always 404, and a CSP/cache-header drift is caught.
 *
 * The actual rendering of Swagger UI happens in the browser. This test
 * validates the server-side gate + response shape, not the JavaScript that
 * swagger-ui-bundle ships.
 *
 * #798 changed two things here. The assets are now served SAME-ORIGIN from
 * `/api/docs/assets/*` instead of jsDelivr, and — the load-bearing half —
 * every script carries the per-request CSP nonce. Without it `script-src`'s
 * `'strict-dynamic'` blocks all three and the page renders an empty div under
 * a 200, which is how it shipped broken for the life of the feature. The
 * nonce-relationship assertions live in `tests/unit/api/docs-route-csp.test.ts`;
 * this file keeps the gate, the headers and the banner.
 */

// The route reads the nonce the middleware sets on the request. Without this
// mock it correctly returns 503 rather than a silently unusable page.
jest.mock('next/headers', () => ({
    headers: async () => ({ get: (k: string) => (k === 'x-csp-nonce' ? 'test-nonce' : null) }),
}));


const { NextRequest } = require('next/server');

function loadRouteFresh() {
    jest.resetModules();

    return require('@/app/api/docs/route');
}

// Epic E — the route is now wrapped with `withApiErrorHandling`,
// which expects a real NextRequest (it reads `req.headers`,
// `req.nextUrl.pathname`, `req.method`). The route handler itself
// still ignores the request, so a stub URL is sufficient.
function fakeRequest() {
    return new NextRequest('http://localhost/api/docs', { method: 'GET' });
}

describe('GET /api/docs — Swagger UI gating', () => {
    const originalEnv = process.env;

    beforeEach(() => {
        process.env = { ...originalEnv };
    });

    afterAll(() => {
        process.env = originalEnv;
    });

    it('returns 404 in production', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'production';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});

        expect(res.status).toBe(404);
        const body = await res.text();
        // Body must not leak any HTML or hint that the route exists —
        // indistinguishable from a route that never existed.
        expect(body).toBe('Not Found');
        expect(body).not.toMatch(/Swagger|swagger|openapi/i);
    });

    it('returns 404 in test (no interactive use during Jest runs)', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'test';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        expect(res.status).toBe(404);
    });

    it('returns 200 + HTML in development', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        const body = await res.text();

        expect(res.status).toBe(200);
        expect(res.headers.get('Content-Type')).toMatch(/text\/html/);
        expect(body).toMatch(/<!DOCTYPE html>/);
        // Page loads the spec from /openapi.json (the static file
        // generated by `npm run openapi:generate`).
        expect(body).toContain("url: '/openapi.json'");
    });

    it('serves Swagger UI assets from our own origin, never a CDN', async () => {
        // Was "via a pinned CDN version" until #798. The pin protected
        // against Swagger 5.x minor drift; the version is now pinned by the
        // `swagger-ui-dist` devDependency in package-lock.json instead, which
        // is a stronger guarantee than a URL string. What replaced the
        // assertion is the property that actually matters: no third-party
        // origin executes on a page we serve.
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        const body = await res.text();

        expect(body).not.toContain('cdn.jsdelivr.net');
        expect(body).not.toMatch(/<script[^>]+src="https?:\/\//);
        expect(body).toContain('/api/docs/assets/swagger-ui.css');
        expect(body).toContain('/api/docs/assets/swagger-ui-bundle.js');
    });

    it('sets dev-friendly cache + robot headers', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});

        expect(res.headers.get('Cache-Control')).toBe('no-store');
        expect(res.headers.get('X-Robots-Tag')).toMatch(/noindex/);
    });

    it('emits a visual DEVELOPMENT banner so screenshots are unambiguous', async () => {
        // Operator-debugging hygiene — a screenshot of the docs page
        // taken from a contributor's machine should make it obvious
        // this isn't production. Removing the banner is a regression.
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        const body = await res.text();

        expect(body).toMatch(/DEVELOPMENT/);
    });
});
